version: '3'
services:
    redis:
      image: redis
      networks:
        - back-end
    db:
      image: postgres:9.4
      networks: 
        - back-end
    # python app
    vote:
      build: ./voting-app
      ports:
        - 5000:80
      depends_on: 
        - redis      
      networks:
        - frond-end
        - back-end
    # nodejs app
    result:
      build: ./result-app
      ports: 
        - 5001:80
      networks:
        - frond-end
        - back-end
    # dotnet app
    worker:
      build: ./worker
      depends_on:
        - redis  
        - postgres    
      networks:
        - back-end
networks:
    frond-end:
    back-end:
# run docker-compose up

         

